---
title: "Scraping a static HTML website"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
```


Go to http://books.toscrape.com/catalogue/page-1.html and scrape the first five pages of data on books with regards to their

- title
- price
- star rating
- availability

Organize your results in a neatly formatted table. 

```{r}
get_books <- function(page) {
  
  base_url <- "http://books.toscrape.com/catalogue/page-"
  url <- str_c(base_url, page, ".html")
  
  books_html <- read_html(url)
  
  prices <- books_html %>% 
    html_nodes(css = ".price_color") %>% 
    html_text()
  
  titles <- books_html %>% 
    html_nodes(css = ".product_pod a") %>% 
    html_attr("title") %>% 
    .[!is.na(.)]
  ratings <- books_html %>% 
    html_nodes(css = ".star-rating") %>% 
    html_attr(name = "class") %>% 
    str_remove(pattern = "star-rating ")
  
  availabilities <- books_html %>% 
    html_nodes(css = ".availability") %>% 
    html_text() %>% 
    str_trim()
  
  books_df <- tibble(
    title     = titles,
    price     = prices,
    rating    = ratings,
    available = availabilities
  )
  
  return(books_df)
}
```

```{r}
# iterate across pages
pages <- 1:5
books <- map_df(pages, get_books)
books
```